### ISSUE TITLE
remove useless code for generating `.zbr-test-run-id`

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/python-agent-robot#5]
as only https://github.com/zebrunner/entrypoint/issues/10 is fixed we don't need anymore functionality which generate `.zbr-test-run-id` file for reference and attaching html/xml reports to launch. Milestone still TBD as related ticket should be fixed first!

**Comment by azarouski** [comment]
PR
---
https://github.com/zebrunner/python-agent-robot/pull/7

TEST
---
Project repository no longer has `.zbr-test-run-id` file
